-- INNER JOIN
SELECT * FROM CIDADES C
INNER JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;

--LEFT JOIN
SELECT * FROM CIDADES C
LEFT JOIN PREFEITOS P 
ON C.ID = P.CIDADE_ID;

--RIGHT JOIN
SELECT * FROM CIDADES
RIGHT JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;

--FULL JOIN - NOT SUPPORTED BY MYSQL
--MUST USE LEFT+RIGHT
SELECT * FROM CIDADES
FULL JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;


SELECT * FROM CIDADES C
LEFT JOIN PREFEITOS P 
ON C.ID = P.CIDADE_ID
UNION
SELECT * FROM CIDADES
RIGHT JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;