SELECT
    REGIAO AS 'REGIÃO',
    SUM(POPULACAO) AS TOTAL
FROM ESTADOS
GROUP BY REGIAO --AGRUPA POR REGIAO
ORDER BY TOTAL DESC;

SELECT 
    SUM(POPULACAO) AS TOTAL --SOH MOSTRA O TOTAL (NUMERO)
FROM ESTADOS;

SELECT
    AVG(POPULACAO) AS TOTAL --VALOR NUMERICO MEDIA
FROM ESTADOS;